# TYPE  DATABASE        USER            ADDRESS                 METHOD

# 允許容器內部連線（健康檢查用）
local   all             all                                     trust

# 所有的網路連線（包含 App）都必須使用密碼
host    all             all             all                     scram-sha-256
