# 允許本機所有連線
local   all             all                                     trust
# 允許 Docker 內部網路連線 (172.16.0.0/12 涵蓋了大多數 Docker 預設網段)
host    all             all             172.16.0.0/12           trust
# 允許外部 DBeaver 連線 (0.0.0.0/0 表示任何 IP，生產環境建議限縮)
host    all             all             0.0.0.0/0               scram-sha-256